export const ADD_POST = 'ADD_POST';
export const CHANGE_SELECTED_POST = 'CHANGE_SELECTED_POST';
export const ADD_POST_REQUEST = 'ADD_POST_REQUEST';
export const ADD_POSTS = 'ADD_POSTS';
export const ADD_SELECTED_POST = 'ADD_SELECTED_POST';
export const DELETE_POST = 'DELETE_POST';

export const GET_BASE_MONS = 'GET_BASE_MONS';
export const GET_ALL_MONS = 'GET_ALL_MONS';
export const CLEAR_ALL_MONS = 'CLEAR_ALL_MONS';
export const GET_ONE_MON = 'GET_ONE_MON';
export const RESET_MON = 'RESET_MON';
export const GET_BASIC_PICK_MONS = 'GET_BASIC_PICK_MONS';

export const GET_LOGIN_MODAL_STATUS = 'GET_LOGIN_MODAL_STATUS';
export const SHOW_LOGIN_MODAL = 'SHOW_LOGIN_MODAL';
export const HIDE_LOGIN_MODAL = 'HIDE_LOGIN_MODAL';

export const GET_MESSAGE_MODAL_STATUS = 'GET_MESSAGE_MODAL_STATUS';
export const SHOW_MESSAGE_MODAL = 'SHOW_MESSAGE_MODAL';
export const HIDE_MESSAGE_MODAL = 'HIDE_MESSAGE_MODAL';
export const PREPARE_MESSAGE_MODAL = 'PREPARE_MESSAGE_MODAL';
export const PREPARE_MESSAGE_MODAL_CONFIRM_ACTION = 'PREPARE_MESSAGE_MODAL_CONFIRM_ACTION';

export const CHECK_APP_MOUNTED = 'CHECK_APP_MOUNTED';
export const GET_APP_MOUNTED = 'GET_APP_MOUNTED';

export const GET_USER_SESSION = 'GET_USER_SESSION';

export const GET_REMEMBERED_USER = 'GET_REMEMBERED_USER';

export const GET_COLLECTION_USER = 'GET_COLLECTION_USER';

export const GET_MONSTER_COUNT_INFO = 'GET_MONSTER_COUNT_INFO';
export const GET_COLLECTION_COUNT_INFO = 'GET_COLLECTION_COUNT_INFO';
export const GET_DESIGNERS = 'GET_DESIGNERS';

export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';

export const SHOW_MON_INFO_FRONT = 'SHOW_MON_INFO_FRONT';
export const SHOW_MON_INFO_BACK = 'SHOW_MON_INFO_BACK';

export const GET_ADDED_ABILITY = 'GET_ADDED_ABILITY';

export const ADD_SELECTED_MON = 'ADD_SELECTED_MON';
export const REMOVE_SELECTED_MON = 'REMOVE_SELECTED_MON';
export const CLEAR_SELECTED_MONS = 'CLEAR_SELECTED_MONS';

export const SET_BEFORE_ACTION = 'SET_BEFORE_ACTION';

export const SET_MENU = 'SET_MENU';

export const ADD_ENTRY_AS_IS = 'ADD_ENTRY_AS_IS';
export const ADD_ENTRY_TO_BE = 'ADD_ENTRY_TO_BE';
export const CLEAR_ENTRY_AS_IS = 'CLEAR_ENTRY_AS_IS';
export const CLEAR_ENTRY_TO_BE = 'CLEAR_ENTRY_TO_BE';

export const GET_ENTRY_STATE = 'GET_ENTRY_STATE';

export const GET_USERS = 'GET_USERS';
export const CLEAR_USERS = 'CLEAR_USERS';
export const ADD_USERS = 'ADD_USERS';

export const GET_RIVAL = 'GET_RIVAL';

export const GET_USER_ENTRY_FOR_BATTLE = 'GET_USER_ENTRY_FOR_BATTLE';
export const GET_RIVAL_ENTRY_FOR_BATTLE = 'GET_RIVAL_ENTRY_FOR_BATTLE';
export const CLEAR_USER_ENTRY_FOR_BATTLE = 'CLEAR_USER_ENTRY_FOR_BATTLE';
export const CLEAR_RIVAL_ENTRY_FOR_BATTLE = 'CLEAR_RIVAL_ENTRY_FOR_BATTLE';

export const GET_FIRST_ATTACK_FLAG = 'GET_FIRST_ATTACK_FLAG';
export const GET_BATTLE_RESULT = 'GET_BATTLE_RESULT';

export const GET_GAME_SPEED = 'GET_GAME_SPEED';

export const SET_HONORS = 'SET_HONORS';
