export const ADD_POST = 'ADD_POST';
export const CHANGE_SELECTED_POST = 'CHANGE_SELECTED_POST';
export const ADD_POST_REQUEST = 'ADD_POST_REQUEST';
export const ADD_POSTS = 'ADD_POSTS';
export const ADD_SELECTED_POST = 'ADD_SELECTED_POST';
export const DELETE_POST = 'DELETE_POST';

export const GET_BASE_MONS = 'GET_BASE_MONS';
export const GET_ALL_MONS = 'GET_ALL_MONS';
export const GET_ONE_MON = 'GET_ONE_MON';
export const RESET_MON = 'RESET_MON';
export const GET_BASIC_PICK_MONS = 'GET_BASIC_PICK_MONS';

export const GET_LOGIN_MODAL_STATUS = 'GET_LOGIN_MODAL_STATUS';
export const SHOW_LOGIN_MODAL = 'SHOW_LOGIN_MODAL';
export const HIDE_LOGIN_MODAL = 'HIDE_LOGIN_MODAL';

export const GET_MESSAGE_MODAL_STATUS = 'GET_MESSAGE_MODAL_STATUS';
export const SHOW_MESSAGE_MODAL = 'SHOW_MESSAGE_MODAL';
export const HIDE_MESSAGE_MODAL = 'HIDE_MESSAGE_MODAL';
export const PREPARE_MESSAGE_MODAL = 'PREPARE_MESSAGE_MODAL';

export const CHECK_APP_MOUNTED = 'CHECK_APP_MOUNTED';
export const GET_APP_MOUNTED = 'GET_APP_MOUNTED';

export const GET_USER_SESSION = 'GET_USER_SESSION';

export const GET_REMEMBERED_USER = 'GET_REMEMBERED_USER';

export const GET_COLLECTION_USER = 'GET_COLLECTION_USER';

export const GET_MONSTER_COUNT_INFO = 'GET_MONSTER_COUNT_INFO';
export const GET_COLLECTION_COUNT_INFO = 'GET_COLLECTION_COUNT_INFO';
export const GET_DESIGNERS = 'GET_DESIGNERS';

export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';
